server:
   port: 7070

mybatis:
  config: classpath:/mybatis/mybatis-config.xml
  typeAliasesPackage: com.hqgd.pms.domain
  mapperLocations: classpath:/mybatis/mapper/*.xml
logging:
  level:
     com.hqgd.pms.dao : debug  
youxing:
   corn1: 0 0 1 ? * *
#   corn1: 0 0/1 * * * ? 
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/pms?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver    
#spring:
#  datasource:
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=pms
#    username: sa
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
spring:
  datasource:
    url: jdbc:sqlserver://47.106.225.170:1433;DatabaseName=HQTemp_Cloud1
    username: sa
    password: dailihui0..
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:D:/image/

#spring:
#  datasource:
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=HQTemp_Cloud1
#    username: sa
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    jpa:
#      database: MYSQL
#  jpa:
#    database: sql_server
#    hibernate:
#      ddl-auto: update
#    show-sql: true     
#    database-platform: org.hibernate.dialect.SQLServer2008Dialect
