server:
   port: 7075

mybatis:
  config: classpath:/mybatis/mybatis-config.xml
  typeAliasesPackage: com.hqgd.pms.domain
  mapperLocations: classpath:/mybatis/mapper/*.xml
#logging:
#  level:
#     com.hqgd.pms.dao : debug  
youxing:
   corn1: 0 0 1 ? * *
#   corn1: 0 0/1 * * * ? 

spring:
  datasource:
    url: jdbc:sqlserver://47.106.225.170:1433;DatabaseName=HQTemp_Cloud1
    username: sa
    password: dailihui0..
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:D:/image/
#hbase:
#  conf:
#    confMaps:
#      'hbase.zookeeper.quorum' : 'uplooking03:2181,uplooking04:2181,uplooking05:2181'

hbase:
  config:
    hbase.zookeeper.quorum: uplooking03:2181,uplooking04:2181,uplooking05:2181
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000
