server:
   port: 8080

mybatis:
  config: classpath:/mybatis/mybatis-config.xml
  typeAliasesPackage: com.hqgd.pms.domain
  mapperLocations: classpath:/mybatis/mapper/*.xml
  

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/pms?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver    
spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.101:1433;DatabaseName=pms
    username: sa
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    jpa:
#      database: MYSQL
#  jpa:
#    database: sql_server
#    hibernate:
#      ddl-auto: update
#    show-sql: true     
#    database-platform: org.hibernate.dialect.SQLServer2008Dialect
